// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import ()

type Todo struct {
	ID      int32  `json:"id"`
	Content string `json:"content"`
	Done    bool   `json:"done"`
	UserID  int32  `json:"userId"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Passwd   []byte `json:"passwd"`
	Salt     string `json:"salt"`
}

type UsersView struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
}
